
/*
1. BASED ON EITHER ELEMENT / STRUCTURE?
2.INTERNAL / EXTERNAL / INPLACE / NOT IN PLACE :- SPACE COMPLEXITY
3. STABLE / NOT STABLE 
4.TIME COMPLEXITY
5.APPROACH :--------1. SUBSTRACT & CONQUER 2. DIVIDE & CONQUER
*/

/*
1. internal /inplace
2. external/not inplace

*/